import requests

words = [
    ('associate', 'wspólnik, kojarzyć'),
    ('assess', 'oceniać'),
    ('legitimate', 'uzasadniony'),
    ('admittedly', 'co prawda, wprawdzie'),
    ('contemporary', 'współczesny'),
    ('ubiquitous', 'wszechobecny'),
    ('brevity', 'zwięzłość'),
    ('comprise', 'zawierać, składać się'),
    ('devour', 'pożerać'),
    ('strive', 'starać się'),
    ('utter', 'kompletny'),
    ('defer', 'opóźniać, odraczać'),
    ('undergo', 'zostać poddanym'),
    ('tedious', 'nudny'),
    ('in turn', 'z kolei'),
    ('immanent', 'nieodłączny'),
    ('merit', 'zasługa'),
    ('severe', 'silny, surowy'),
    ('thorough', 'gruntowny, dokładny'),
    ('throughout', 'w całym'),
    ('eminent', 'wybitny'),
    ('decoupled', 'oddzielony'),
    ('composite', 'łączny'),
    ('detour', 'objazd'),
    ('admit', 'przyznawać się, wpuszczać'),
    ('accordingly', 'w związku z tym, odpowiednio'),
    ('depict', 'przedstawiać'),
    ('conceive', 'obmyślić, pojąć'),
    ('reminiscent', 'pamiętny'),
    ('superficial', 'powierzchowny'),
    ('robust', 'silny, solidny'),
    ('elaborate', 'opracować, rozwijać, dopracowany, zawiły'),
    ('leap', 'skok'),
    ('intricate', 'zawiły'),
    ('contrive', 'obmyślać'),
    ('notion', 'pojęcie'),
    ('compliant', 'zgodny'),
    ('intimidate', 'zastraszać'),
    ('prominent', 'wybitny'),
    ('protuberant', 'wypukły'),
    ('in terms of', 'jeśli chodzi o, pod względem, z punktu widzenia'),
    ('vulnerable', 'podatny'),
    ('leverage', 'wpływ, wykorzystać'),
    ('eligible', 'nadający się'),
    ('deliberate', 'celowy, przemyślany, rozważać'),
    ('substantial', 'znaczny'),
    ('compartment', 'przegroda'),
    ('concise', 'zwięzły'),
    ('oath', 'przysięga, przekleństwo'),
    ('derelict', 'porzucony'),
    ('endow', 'obdarzyć'),
    ('nudge', 'trącić'),
    ('thaw', 'odwilż, rozmrażać'),
    ('bifurcate', 'rozwidlać się'),
    ('dispatch', 'wysyłać'),
    ('summit', 'szczyt, wierzchołek'),
    ('retain', 'zachować'),
    ('prone', 'skłonny'),
    ('prune', 'redukować, przycinać'),
    ('implicit', 'domniemany'),
    ('explicit', 'wyraźny'),
    ('distinct', 'oddzielny, wyrazisty'),
    ('rupture', 'pęknięcie'),
    ('reciprocal', 'odwrotność, wzajemny, obustronny'),
    ('obsolete', 'przestarzały'),
    ('constraint', 'ograniczenie, przymus'),
    ('insolence', 'zuchwałość'),
    ('comprehend', 'zrozumieć'),
    ('comprehensible', 'zrozumiały'),
    ('comprehensive', 'wszechstronny, pełny'),
    ('auxiliary', 'pomocniczy'),
    ('forsake', 'porzucic'),
    ('ancestry', 'pochodzenie'),
    ('recipient', 'odbiorca'),
    ('sake', 'wzgląd'),
    ('endeavour', 'usiłować, dążenie'),
    ('retrieve', 'odzyskać'),
    ('retract', 'wycofać'),
    ('commit', 'powierzać, oddać'),
    ('commitment', 'zobowiązanie'),
    ('aggregate', 'sumaryczny'),
    ('stash', 'schować na potem'),
    ('amend', 'poprawić'),
    ('vicious', 'zły, złośliwy'),
    ('loom', 'wynurzać się (z mgły)'),
    ('twine', 'wykręcać'),
    ('bundle', 'wiązka'),
    ('invoke', 'odwołać się, wezwać'),
    ('scaffolding', 'rusztowanie'),
    ('tenant', 'lokator'),
    ('rampart', 'wał'),
    ('decent', 'przyzwoity'),
    ('precede', 'poprzedzać'),
    ('obliterate', 'wymazać'),
    ('latter', 'drugi'),
    ('encounter', 'natknąć się, starcie'),
    ('clutter', 'nieład'),
    ('cluster', 'grupa'),
    ('superfluous', 'zbędny'),
    ('unobtrusive', 'dyskretny'),
    ('descendant', 'potomek'),
    ('unlikely', 'mało prawdopodobne'),
    ('repel', 'odpychać'),
    ('barley', 'jęczmień'),
    ('wheat', 'pszenica'),
    ('yeast', 'drożdże'),
    ('maize', 'kukurydza'),
    ('ripen', 'dojrzewać'),
    ('outweigh', 'przeważać'),
    ('perimeter', 'obwód'),
    ('despicable', 'podły'),
    ('synopsis', 'streszczenie'),
    ('concurrent', 'współbieżny'),
    ('coincident', 'zbieżny, zgodny, równoczesny'),
    ('plausible', 'prawdopodobny, wiarygodny'),
    ('parcel', 'paczka'),
    ('dignity', 'godność'),
    ('persistent', 'trwały'),
    ('ellipsis', 'wielokropek'),
    ('seal off', 'zamykać dostęp do'),
    ('breach', 'wyłom, przełamać'),
    ('spurious', 'nieprawdziwy'),
    ('ambiguous', 'dwuznaczny'),
    ('ostensibly', 'rzekomo'),
    ('propriety', 'stosowność'),
    ('proprietary', 'własny, firmowy'),
    ('scarce', 'deficytowy, rzadki, ograniczony'),
    ('quotas', 'przydział'),
    ('bias', 'odchyłka, stronniczość, uprzedzenie'),
    ('cater', 'zaopatrywać'),
    ('cumbersome', 'niewygodny'),
    ('payload', 'ładunek'),
    ('sentry', 'wartownik'),
    ('suffice', 'wystarczać'),
    ('designate', 'wyznaczać'),
    ('denote', 'oznaczyć'),
    ('tier', 'poziom, warstwa'),
    ('subsequent', 'późniejszy'),
    ('frontier', 'granica'),
    ('depiction', 'opis'),
    ('invoice', 'faktura'),
    ('inference', 'wnioskowanie'),
    ('crucial', 'rozstrzygający'),
    ('suppress', 'stłumić'),
    ('affinity', 'podobieństwo'),
    ('augmented', 'rozszerzony'),
    ('inhabitant', 'mieszkaniec'),
    ('mock', 'próbny'),
    ('intercept', 'przechwytywać'),
    ('decline', 'spadek, podupadać'),
    ('cognitive', 'poznawczy'),
    ('contiguous', 'przyległy'),
    ('collate', 'zestawić'),
    ('verbatim', 'dosłownie'),
    ('coercion', 'wymuszenie, przymus'),
    ('thoroughly', 'całkowicie'),
    ('unattended', 'bez nadzoru'),
    ('nonetheless', 'pomimo to'),
    ('precedence', 'pierwszeństwo'),
    ('pedigree', 'rodowód'),
    ('solely', 'jedynie, wyłącznie'),
    ('merely', 'jedynie'),
    ('conform', 'dostosowywać się'),
    ('contradiction', 'sprzeczność'),
    ('compel', 'zmuszać'),
    ('inhibit', 'powstrzymywać'),
    ('verity', 'prawda'),
    ('recede', 'cofać się'),
    ('scatter', 'rozrzucać, rozproszyć się'),
    ('bulk', 'hurt'),
    ('evade', 'unikać'),
    ('assessment', 'oszacowanie'),
    ('abruptly', 'nagle'),
    ('perseverance', 'wytrwałość'),
    ('hence', 'stąd'),
    ('resort', 'uciekać się, uciekanie się'),
    ('as a last resort', 'w ostateczności'),
    ('invariant', 'niezmienny'),
    ('sophisticated', 'wyrafinowany'),
    ('refer to', 'oznaczać, odnosić się do, korzystać z'),
    ('due to', 'z powodu'),
    ('tread', 'chód, bieżnik'),
    ('reluctant', 'niechętny'),
    ('consecutive', 'kolejny'),
    ('stare', 'gapić się'),
    ('viral', 'wirusowy'),
    ('subvert', 'obalać'),
    ('dormant', 'bezczynny, śpiący'),
    ('fragrance', 'zapach'),
    ('stake', 'kołek, stawka, obstawiać'),
    ('streak', 'pasmo, smuga'),
    ('sustain', 'podtrzymywać'),
    ('spree', 'hulanka, szał'),
    ('perpetual', 'wieczny'),
    ('lurk', 'czaić się'),
    ('peek', 'zerkać'),
    ('peak', 'szczyt'),
    ('compulsory', 'przymusowy'),
    ('bizarre', 'dziwaczny'),
    ('ultimate', 'ostateczny, największy'),
    ('latch', 'zatrzask'),
    ('grieve', 'smucić się'),
    ('mutually', 'wzajemnie'),
    ('cohesion', 'spójność'),
    ('revoke', 'unieważniać'),
    ('endurance', 'wytrzymałość'),
    ('diminish', 'pomniejszać'),
    ('disrupt', 'zakłócać, krzyżować'),
    ('altogether', 'całkowicie, generalnie'),
    ('yield', 'zysk, przynosić plon, ustępować'),
    ('negligible', 'nieistotny'),
    ('albeit', 'aczkolwiek'),
    ('thyme', 'tymianek'),
    ('prior to', 'przed'),
    ('extent', 'zakres, zasięg'),
    ('surplus', 'nadmiar, nadmiarowy'),
    ('breed', 'hodować'),
    ('thus', 'a zatem'),
    ('remarkable', 'nadzwyczajny'),
    ('mediocre', 'przeciętny, mierny'),
    ('meaningful', 'sensowny'),
    ('my bias', 'moje podejście, nastawienie, punkt widzenia'),
    ('twofold', 'dwojaki'),
    ('grasp', 'chwycić, zrozumieć'),
    ('grab', 'chwycić, złapać'),
    ('canvas', 'płótno np do malowania, pojęcie wykorzystywane w programowaniu w kontekście rysowania grafik'),
    ('stilted', 'nienaturalny'),
    ('invaluable', 'nieceniony'),
    ('prevents', 'zapobiega'),
    ('explicitly', 'wyraźnie'),
    ('strive', 'starać się'),
    ('exhausting', 'wyczerpujący'),
    ('internally', 'wewnętrznie'),
    ('obscured', 'zasłonięte'),
    ('reminiscing', 'przywoływanie wspomnień'),
    ('coverage', 'reportaż, omówienie prasowe, pokrycie'),
    ('comprehensive', 'wszechstronny, obszerny'),
    ('efforts', 'starania'),
    ('press release', 'komunikat prasowy'),
    ('fees', 'opłaty'),
    ('redeem', 'wykupić, odkupić'),
    ('audit', 'sprawdzenie, rewizja'),
    ('sublime', 'wzniosły, idealny, wysublimowany'),
    ('contribute', 'przyczynić się, wnieść wkład'),
    ('utilize', 'wykorzystać, eksploatować'),
    ('prompt', 'skłonić, namówić'),
    ('assumption', 'założenie, hipoteza'),
    ('attempt', 'próba, usiłowanie'),
    ('appropriate', 'właściwy, stosowny'),
    ('robust', 'silny, krzepki'),
    ('home theater', 'kino domowe'),
    ('puberty', 'dojrzewanie płciowe'),
    ('omitting', 'pomijać'),
    ('consecutive', 'kolejny, nieprzerwany, seryjny, następujący po czymś'),
    ('auxiliary', 'Pomocniczy, posiłkowy'),
    ('scheduled', 'planowy'),
    ('suppress', 'stłumić, znieść'),
    ('declined', 'odrzucony'),
    ('quote', 'cytować'),
    ('tender', 'delikatny'),
    ('wreck', 'wrak'),
    ('tribute', 'hołd, uznanie'),
    ('explicit', 'wyraźny, kategoryczny'),
    ('white paper', 'dokument reklamujący jakiś produkt ( ma jeszcze inne znaczenia )'),
    ('resource efficiency', 'efektywność wykorzystania zasobów'),
    ('sequality', 'sekwencja'),
    ('executive', 'wykonawczy'),
    ('executive summary', 'streszczenie'),
    ('redeem', 'wykupić, odkupić'),
    ('stilted', 'nienaturalny, wymuszony'),
    ('twofold', 'dwojaki, dwukrotny'),
    ('sublime', 'wzniosły, idealny, wysublimowany'),
    ('grasp', 'chwytać, zrozumieć'),
    ('ward', 'oddział, dzielnica'),
    ('conceal', 'ukrywać'),
    ('respectively', 'odpowiednio'),
    ('resilient', 'sprężysty'),
    ('postpone', 'odraczać'),
    ('reconcile', 'pogodzić'),
    ('state of the art', 'współczesny stan wiedzy'),
    ('overhaul', 'remontować, przegląd'),
    ('primordial', 'pierwotny'),
    ('cogged', 'zębaty'),
    ('rack', 'półka, stojak'),
    ('tremble', 'drżeć'),
    ('anxiety', 'niepokój'),
    ('frail', 'słaby, wątły'),
    ('sip', 'łyk'),
    ('audible', 'słyszalny'),
    ('discretionary', 'nieobowiązkowy'),
    ('spouse', 'małżonek, małżonka'),
    ('consolation', 'pocieszenie'),
    ('stand by', 'być gotowym, wspierać'),
    ('hang around', 'pałętać się'),
    ('beguile', 'mamić'),
    ('toss', 'rzucać'),
    ('tentative', 'niepewny, wstępny'),
    ('grim', 'ponury'),
    ('alike', 'podobnie, podobny'),
    ('swell', 'narastać'),
    ('menace', 'groźba, zagrożenie'),
    ('quarrel', 'kłótnia, kłócić się'),
    ('premises', 'siedziba, teren'),
    ('compulsive', 'przymusowy'),
    ('chairman', 'przewodniczący, prezes'),
    ('diffuse', 'rozproszony'),
    ('be at the mercy of', 'być zdanym na łaskę'),
    ('disparity', 'nierówność'),
    ('infringement', 'naruszenie'),
    ('diversity', 'różnorodność'),
    ('admissible', 'dopuszczalny'),
    ('neat', 'staranny'),
    ('superior', 'lepszy, starszy'),
    ('shortcoming', 'mankament, niedostatek'),
    ('discrepancy', 'rozbieżność'),
    ('feasible', 'wykonalny'),
    ('neglect', 'zaniedbywać, zaniedbanie'),
    ('excerpt', 'urywek, fragment, wyjątek'),
    ('burden', 'obciążenie'),
    ('suitable', 'odpowiedni'),
    ('extraneous', 'uboczny'),
    ('overcome', 'przezwyciężać'),
    ('opinionated', 'zawzięty, zadufany'),
    ('successor', 'następca'),
    ('efficient', 'wydajny'),
    ('effective', 'skuteczny'),
    ('vague', 'niejasny'),
    ('receptacle', 'gniazdo (wtykowe)'),
    ('slack', 'luźny'),
    ('affection', 'uczucie'),
    ('gratitude', 'wdzięczność'),
    ('attain', 'osiągnąć'),
    ('loathe', 'nienawidzić'),
    ('revise', 'poprawić'),
    ('intermediary', 'pośrednik'),
    ('caveat', 'zastrzeżenie'),
    ('interim', 'tymczasowy, przejściowy'),
    ('inherently', 'z natury'),
    ('innocuous', 'nieszkodliwy'),
    ('opt out', 'zrezygnować'),
    ('in moderation', 'z umiarem'),
    ('disclose', 'ujawniać'),
    ('harsh', 'surowy, ostry'),
    ('cease', 'ustawać'),
    ('stale', 'nieświeży'),
    ('condemn', 'potępiać, skazywać'),
    ('gist', 'esencja, sedno'),
    ('fortnightly', 'dwutygodniowy'),
    ('firmly', 'stanowczo, pewnie'),
    ('bogus', 'fałszywy, podrobiony'),
    ('envy', 'zazdrość'),
    ('prevail', 'przeważać'),
    ('chasm', 'przepaść'),
    ('rejoice', 'cieszyć się'),
    ('perceive', 'postrzegać'),
    ('incorporate', 'włączać w, zawierać'),
    ('exaggerate', 'wyolbrzymiać'),
    ('urge', 'pragnienie, namawiać'),
    ('converge', 'zbiegać się'),
    ('disregard', 'lekceważyć'),
    ('lucrative', 'dochodowy'),
    ('retaliation', 'odwet'),
    ('tamper with', 'ingerować, majstrować przy'),
    ('tinker with', 'majstrować przy'),
    ('unravel', 'rozwikłać'),
    ('commotion', 'zamieszanie'),
    ('overlap', 'zakładka, zachodzić'),
    ('endorse', 'popierać'),
    ('intrinsic', 'wrodzony'),
    ('reckon', 'przypuszczać, szacować'),
    ('praise', 'pochwała'),
    ('churlish', 'chamski'),
    ('enhance', 'ulepszać'),
    ('somber', 'ponury'),
    ('deliberately', 'celowo'),
    ('humiliate', 'poniżać'),
    ('siblings', 'rodzeństwo'),
    ('taint', 'zanieczyszczać'),
    ('detention', 'przetrzymanie'),
    ('reassuring', 'uspokajający'),
    ('insidious', 'podstępny, zdradziecki'),
    ('elusive', 'nieuchwytny, ulotny'),
    ('proficiency', 'biegłość'),
    ('comprehension', 'zrozumienie'),
    ('circumvent', 'omijać, obejść'),
    ('goofy', 'głupkowaty'),
    ('hilarious', 'zabawny, komiczny'),
    ('promptly', 'natychmiast'),
    ('namely', 'a mianowicie'),
    ('supersede', 'wypierać, zastąpić'),
    ('chassis', 'podwozie'),
    ('arbitrary', 'dowolny, przypadkowy'),
    ('preliminary', 'wstępny'),
    ('conscientious', 'sumienny'),
    ('anticipate', 'przewidywać'),
    ('behold', 'ujrzeć'),
    ('self-esteem', 'samoocena'),
    ('thrive', 'rozwijać się, prosperować'),
    ('impose', 'nakładać'),
    ('conceivable', 'wyobrażalny'),
    ('rectify', 'prostować'),
    ('daunting', 'zniechęcający'),
    ('incentive', 'zachęta, bodziec'),
    ('tackle', 'podejmować walkę z'),
    ('clumsy', 'niezdarny'),
    ('come across', 'natknąć się'),
    ('afterall', 'ostatecznie'),
    ('refrain', 'powstrzymywać się'),
    ('insight', 'wgląd, spostrzeżenie'),
    ('non-intrusive', 'nieinwazyjny'),
    ('mitigate', 'załagodzić'),
    ('thrift', 'oszczędność, zapobiegliwość'),
    ('haphazard', 'przypadkowy, bezplanowy'),
    ('fornication', 'cudzołóstwo'),
    ('afterwards', 'potem'),
    ('settle', 'osiadać, rozstrzygać, uregulować'),
    ('hang out', 'spędzać czas'),
    ('condiment', 'przyprawa'),
    ('stumble', 'potknąć się'),
    ('stutter', 'jąkać się'),
    ('carry on', 'kontynuować'),
    ('carry out', 'wykonać'),
    ('congestion', 'zator'),
    ('incur', 'ponieść'),
    ('negligence', 'niedbalstwo'),
    ('recall', 'przypominać, wycofać'),
    ('frame', 'wrobić kogoś'),
    ('exempt', 'zwolniony'),
    ('trespass', 'wykroczenie'),
    ('lodge', 'zakwaterować'),
    ('subdue', 'podbić'),
    ('subside', 'zapadać'),
    ('struggle', 'zmagać się'),
    ('sore', 'ból'),
    ('confined', 'ograniczony, zamknięty'),
    ('dent', 'wygiąć, wygięcie'),
    ('dispense', 'rozdzielać, rozdać'),
    ('signpost', 'drogowskaz'),
    ('remit', 'przekazać'),
    ('ramp', 'pochylnia'),
    ('dwell', 'mieszkać'),
    ('facility', 'placówka, łatwość'),
    ('virtually', 'prawie, właściwie'),
    ('adverse', 'niekorzystny'),
    ('inquire', 'pytać się'),
    ('compassion', 'współczucie'),
    ('dash', 'pędzić'),
    ('downright', 'szczery, skończony, jawny'),
    ('imminent', 'nieuchronny'),
    ('revenue', 'dochód'),
    ('at last', 'wreszcie'),
    ('faint', 'wątły'),
    ('inevitable', 'nieunikniony'),
    ('distress', 'rozpacz, w niebezpieczeństwie'),
    ('vanquish', 'pokonać, zwyciężyć'),
    ('bail', 'kaucja'),
    ('be in charge of', 'być odpowiedzialnym za'),
    ('deflect', 'uginać, odpierać, odchylać'),
    ('undoing', 'zguba'),
    ('take care', 'zadbać, zatroszczyć się'),
    ('in a manner of speaking', 'w pewnym sensie'),
    ('gratuitous', 'darmowy, bezinteresowny'),
    ('diversify', 'urozmaicać'),
    ('nuisance', 'utrapienie'),
    ('in the wake of', 'w następstwie'),
    ('subterranean', 'podziemny'),
    ('lore', 'wiedza'),
    ('contagious', 'zaraźliwy'),
    ('runny nose', 'katar'),
    ('juvenile', 'nieletni'),
    ('contrail', 'smuga'),
    ('vapor', 'para'),
    ('muffle', 'stłumić, okryć'),
    ('doodle', 'gryzmolić'),
    ('twitch', 'skurcz, drganie'),
    ('blooper', 'wpadka'),
    ('overkill', 'przesada'),
    ('perplex', 'zakłopotanie, wprawiać w zakłopotanie'),
    ('plead', 'błagać, bronić, przyznać się'),
    ('lenient', 'pobłażliwy, łagodny'),
    ('renounce', 'wyrzec się'),
    ('recoil', 'odrzut'),
    ('topple', 'obalać, przewracać się'),
    ('martial', 'wojenny'),
    ('indulge', 'pobłażać, dogadzać'),
    ('dismantle', 'zdemontować'),
    ('nourishment', 'pokarm'),
    ('turd', 'łajno'),
    ('on behalf of', 'w imieniu'),
    ('devise', 'wymyślać, wynaleźć, zaplanować'),
    ('commission', 'prowizja, zlecenie'),
    ('impede', 'utrudniać, wstrzymywać'),
    ('puberty', 'dojrzewanie'),
    ('righteous', 'sprawiedliwy, słuszny'),
    ('hideous', 'ohydny, obrzydliwy'),
    ('yank', 'szarpać'),
    ('refute', 'obalić, odeprzeć zarzuty'),
    ('shove', 'pchnięcie'),
    ('pity', 'szkoda, litość, współczucie'),
    ('allure', 'nęcić, wabić'),
    ('coy', 'skromny, nieśmiały'),
    ('vindicate', 'bronić, dowieść czegoś'),
    ('expel', 'wydalać'),
    ('venture', 'ryzyko, przedsięwzięcie'),
    ('pledge', 'zastaw, zobowiązać się'),
    ('pottery', 'garncarstwo'),
    ('conjecture', 'przypuszczenie'),
    ('flutter', 'trzepotać, niepokój'),
    ('rot', 'gnić'),
    ('rein', 'trzymać na wodzy'),
    ('self-contained', 'samodzielny, samowystarczalny'),
    ('undergoing', 'w trakcie, przechodzący'),
    ('sigh', 'westchnąć'),
    ('secretion', 'wydzielina'),
    ('outrage', 'skandal, zniewaga'),
    ('rile', 'złościć, irytować'),
    ('downcast', 'przygnębiony'),
    ('sidekick', 'pomocnik'),
    ('seemingly', 'ponoć, pozornie'),
    ('displace', 'przesiedlać, wypierać'),
    ('soar', 'wznieść się'),
    ('slump', 'osunąć, gwałtownie spadać'),
    ('outnumber', 'przewyższać liczebnie'),
    ('mumble', 'mamrotać, bełkotać'),
    ('stiff', 'sztywny, oschły'),
    ('pensive', 'zamyślony'),
    ('profusely', 'obficie'),
    ('prop', 'rekwizyt, podpierać'),
    ('shatter', 'roztrzaskać'),
    ('plummet', 'spadać'),
    ('sinister', 'złowrogi, złowieszczy'),
    ('subsidiary', 'drugorzędny, pomocniczy'),
    ('overtone', 'podtekst'),
    ('skirmish', 'potyczka'),
    ('competitive', 'konkurencyjny'),
    ('coalesce', 'łączyć, zjednoczyć się'),
    ('supremacy', 'zwierzchnictwo, przewaga'),
    ('at most', 'co najwyżej'),
    ('secluded', 'odosobniony'),
    ('outright', 'wprost, otwarcie'),
    ('be fed up with', 'mieć dość'),
    ('inconsiderate', 'nieuprzejmy, nierozważny'),
    ('bleach', 'wybielić'),
    ('exalt', 'wywyższać, wychwalać'),
    ('sloppy', 'niechlujny, zaniedbany'),
    ('petty', 'drobny, mało ważny'),
    ('saddle', 'siodło'),
    ('allegedly', 'rzekomo'),
    ('luxuriate', 'rozkoszować się'),
    ('strangle', 'udusić'),
    ('abundant', 'obfity, szczodry'),
    ('overdue', 'zaległy, spóźniony'),
    ('crave', 'pragnąć, pożądać'),
    ('ominous', 'złowieszczy, złowrogi, groźny'),
    ('scarcity', 'niedobór, niedostatek'),
    ('hollow', 'pusty, wydrążony'),
    ('crude', 'surowy, nieokrzesany'),
    ('savage', 'dziki, brutalny'),
    ('apex', 'wierzchołek, szczyt'),
    ('spur', 'pobudzać, zachęcać'),
    ('avenge', 'mścić'),
    ('custard', 'krem'),
    ('worrisome', 'niepokojący'),
    ('kinky', 'perwersyjny, zboczony'),
    ('tickle', 'łaskotać'),
    ('resent', 'oburzać się, obrazić się'),
    ('attend', 'brać udział w, asystować, troszczyć się'),
    ('cutlery', 'sztućce'),
    ('hustle', 'pośpiech, popędzać'),
    ('provision', 'zaopatrzeć, zabezpieczać'),
    ('stall', 'ugrzęznąć, blokować, stoisko'),
    ('stickler', 'pedant, skrupulant'),
    ('mutiny', 'bunt, buntować się'),
    ('inferior', 'podrzędny, gorszy, podwładny'),
    ('loiter', 'wałęsać się'),
    ('installment', 'rata'),
    ('jeopardy', 'niebezpieczeństwo'),
    ('rudimentary', 'prymitywny, elementarny'),
    ('omnipotent', 'wszechmocny'),
    ('revamp', 'przerabiać, odnawiać'),
    ('refurbishment', 'remont'),
    ('bleak', 'ponury, blady'),
    ('topical', 'miejscowy, tematyczny'),
    ('damper', 'amortyzator'),
    ('beet', 'burak'),
    ('contamination', 'zanieczyszczenie'),
    ('consent', 'zgoda, pozwolenie, zgodzić się'),
    ('scrutinize', 'lustrować, badać szczegółowo'),
    ('imply', 'sugerować, implikować'),
    ('vessel', 'naczynie, okręt'),
    ('sly', 'chytry, cwany'),
    ('swollen', 'spuchnięty'),
    ('rub', 'pocierać'),
    ('butler', 'lokaj'),
    ('keen', 'zapalony, chętny, przenikliwy'),
    ('pushy', 'natrętny'),
    ('booze', 'gorzałka'),
    ('bog', 'bagno, zapadać'),
    ('molten', 'ciekły, stopiony'),
    ('phase out', 'wycofać się'),
    ('inexplicable', 'niewytłumaczalny'),
    ('pension', 'emerytura, renta, pensjonat'),
    ('reek', 'smród'),
    ('wind up', 'zakończyć się, nakręcić'),
    ('rave', 'bredzić, wściekać się'),
    ('prudent', 'rozważny, ostrożny'),
    ('futile', 'daremny, bezcelowy, próżny'),
    ('hoist', 'wyciągać, podnieść'),
    ('mellow', 'łagodny, spokojny'),
    ('hussy', 'lafirynda'),
    ('spat', 'sprzeczka'),
    ('outrageous', 'skandaliczny'),
    ('obtuse', 'tępy, niezdolny, rozwartokątny'),
    ('demote', 'zdegradować'),
    ('convertible', 'kabriolet, zamienny'),
    ('bride', 'panna młoda'),
    ('groom', 'pan młody'),
    ('giggle', 'chichotać'),
    ('shun', 'unikać kogoś'),
    ('quilt', 'kołdra'),
    ('perks', 'benefity'),
    ('interference', 'ingerencja, interwencja'),
    ('tether', 'spętać'),
    ('cleavage', 'dekolt, szczelina'),
    ('felony', 'przestępstwo, zbrodnia'),
    ('disgruntled', 'niezadowolony'),
    ('tardiness', 'opóźnienie, powolność'),
    ('cherish', 'miłować'),
    ('repulsive', 'odpychający'),
    ('in accordance with', 'w zgodzie z'),
    ('mob', 'tłum'),
    ('vigilant', 'czujny'),
    ('villain', 'łotr, złoczyńca'),
    ('wayward', 'samowolny, kapryśny, nieobliczalny'),
    ('exquisite', 'wyśmienity'),
    ('trinket', 'błyskotka, drobiazg'),
    ('brittle', 'kruchy'),
    ('admonish', 'upominać'),
    ('perpetrator', 'sprawca, przestępca'),
    ('on the fritz', 'zepsuty'),
    ('reckless', 'lekkomyślny, brawurowy'),
    ('daredevil', 'chojrak, śmiałek'),
    ('complicit', 'współudział'),
    ('ditty', 'śpiewka'),
    ('demise', 'zgon'),
    ('specimen', 'okaz'),
    ('gawky', 'gamoniowaty'),
    ('lousy', 'parszywy, wstrętny'),
    ('induce', 'wywołać, spowodować'),
    ('relentless', 'bezlitosny'),
    ('phoney', 'fałszywy, udawany'),
    ('nexus', 'ogniwo'),
    ('baffled', 'zdumiony, zmieszany'),
    ('limbo', 'otchłań, zapomnienie'),
    ('troublesome', 'kłopotliwy'),
    ('utmost', 'najwyższy'),
    ('conjure', 'czarować'),
    ('manifold', 'wieloraki, różnorodny, rozgałęzienie'),
    ('climax', 'punkt kulminacyjny'),
    ('turnstile', 'bramka, kołowrót'),
    ('soothe', 'łagodzić'),
    ('alas', 'niestety'),
    ('divert', 'odwracać, odciągnąć'),
    ('coerce', 'przumusić'),
    ('effigy', 'wizerunek'),
    ('collateral', 'dodatkowy'),
    ('reciprocate', 'odwzajemniać'),
    ('incest', 'kazirodztwo'),
    ('sham', 'pozorny'),
    ('daft', 'stuknięty'),
    ('awe', 'groza'),
    ('bummer', 'porażka'),
    ('pecker', 'kutas'),
    ('aptly', 'trafnie'),
    ('cunning', 'przebiegły'),
    ('staggering', 'oszałamiający'),
    ('tangible', 'namacalny'),
    ('cellar', 'piwnica'),
    ('utterly', 'całkowicie'),
    ('grove', 'gaj'),
    ('flint', 'krzemień'),
    ('animaln hide', 'skóra zwierzęca'),
    ('herd', 'stado'),
    ('lumpy', 'grudkowaty'),
    ('unwary', 'nieostrożny'),
    ('manure', 'nawóz'),
    ('inadvertent', 'nieumyślny'),
    ('fallacy', 'błąd'),
    ('aftermath', 'następstwa'),
    ('deceased', 'zmarły'),
    ('by means of', 'za pomocą'),
    ('inquisitive', 'ciekawy, dociekliwy'),
    ('sanitize', 'odkażać'),
    ('brag', 'przechwalać się'),
    ('forfeit', 'utracić'),
    ('dwelling', 'mieszkanie'),
    ('convoluted', 'zawiły, zagmatwany'),
    ('unseemly', 'nieprzyzwoity'),
    ('predicament', 'kłopotliwe położenie'),
    ('potent', 'silny, skuteczny'),
    ('grub', 'żarcie, czerw'),
    ('apprehensive', 'lękliwy'),
    ('unruly', 'niesforny'),
    ('venison', 'dziczyzna'),
    ('hoof', 'kopyto'),
    ('abide', 'przestrzegać'),
    ('wary', 'ostrożny'),
    ('stow', 'schować'),
    ('errand', 'zadanie'),
    ('stew', 'gulasz'),
    ('apprentice', 'uczeń'),
    ('hassle', 'kłopot'),
    ('culprit', 'winowajca'),
    ('paramount', 'najważniejszy, główny'),
    ('hefty', 'masywny, mocny'),
    ('whimsical', 'kapryśny, cudaczny'),
    ('abomination', 'wstręt, paskudztwo'),
    ('demeaning', 'poniżający'),
    ('considerate', 'uważny, taktowny'),
    ('succumb', 'ulec'),
    ('concur', 'zgodzić się, zbiegać'),
    ('picky', 'wybredny'),
    ('picky', 'wybredny'),
    ('indifferent', 'obojętny, apatyczny, nieszczególny'),
    ('stroke', 'udar, uderzenie, głaskać'),
    ('incline', 'skłaniać się'),
    ('alleviate', 'łagodzić, uśmierzać'),
    ('brat', 'bachor'),
    ('slowpoke', 'ślamazara'),
    ('uncanny', 'przedziwny, niesamowity'),
    ('cringe', 'żenada, kulić się'),
    ('profound', 'dogłębny'),
    ('wholesome', 'zdrowy'),
    ('ingenious', 'pomysłowy, kunsztowny'),
    ('toil', 'natrudzić'),
    ('bugger', 'o kurwa!, pederasta'),
    ('innate', 'wrodzony'),
    ('to no avail', 'bezskutecznie'),
    ('deteriorate', 'pogarszać się'),
    ('aforementioned', 'wyżej wymieniony'),
    ('grudgingly', 'niechętnie'),
    ('slumber', 'sen, drzemka'),
    ('woe', 'nieszczęście, niedola'),
    ('ponder', 'rozważać, zastanawiać się'),
    ('bicker', 'sprzeczać się'),
    ('delve', 'grzebać, zagłębiać się'),
    ('ameliorate', 'ulepszać'),
    ('unwittingly', 'bezwiednie'),
    ('subliminal', 'podświadomy'),
    ('far-fetched', 'naciągany'),
    ('infuriate', 'rozwścieczać, denerwować'),
    ('trifle', 'drobiazg'),
    ('sluggish', 'ślamazarny, powolny'),
    ('wits', 'rozum'),
    ('prejudiced', 'uprzedzony, nieprzychylny'),
    ('disruptive', 'zakłócający, niszczący'),
    ('treachery', 'zdrada'),
    ('eradicate', 'likwidować'),
    ('brawl', 'bijatyka'),
    ('incidentally', 'nawiasem mówiąc'),
    ('insatiable', 'nienasycony'),
    ('dilute', 'rozcieńczać'),
    ('inherent', 'nieodłączny'),
    ('reportedly', 'podobno'),
    ('sentient', 'odczuwający'),
    ('grievance', 'skarga, pretensja'),
    ('testimony', 'świadectwo, zeznanie'),
    ('procure', 'zdobyć, postarać się'),
    ('edible', 'jadalny'),
    ('undermine', 'osłabiać'),
    ('immense', 'niezmierny'),
    ('quaint', 'oryginalny, ciekawy'),
    ('conceivably', 'potencjalnie, prawdopodobnie'),
    ('muddle', 'zamęt, bałagan'),
    ('premise', 'przesłanka'),
    ('exhilarating', 'radosny'),
    ('grind', 'harówka, miażdżyć'),
    ('feisty', 'zadziorny'),
    ('overzealous', 'nadgorliwy'),
    ('birch', 'brzoza'),
    ('plunge', 'nurkować'),
    ('fleeting', 'przelotny'),
    ('whine', 'jęczeć, marudzić'),
    ('unbearable', 'nieznośny'),
    ('unanimously', 'jednogłośnie'),
    ('illicit', 'nielegalny'),
    ('tacit', 'milczący'),
    ('entrails', 'wnętrzności, flaki'),
    ('divest', 'pozbyć się'),
    ('imprudent', 'nieroztropny'),
    ('fussy', 'wybredny'),
    ('deterrent', 'odstraszający'),
    ('influx', 'napływ'),
    ('envoy', 'wysłannik'),
    ('oversee', 'nadzorować'),
    ('entail', 'pociągać za sobą'),
    ('prospect', 'perspektywa, możliwość'),
    ('watch over', 'pilnować'),
    ('resemble', 'przypominać, być podobnym do'),
]


for name, definition in words:
    r = requests.post('http://localhost:8000/webdict/api/word', 
        json={'word': name, 'definition': definition, 'dictionaryCode': 'en-pl', 'userId': '1'})
    r.raise_for_status()
